/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as EnBlogRouteImport } from './routes/en.blog'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as EnBlogIndexRouteImport } from './routes/en.blog.index'
import { Route as EnBlogSlugRouteImport } from './routes/en.blog.$slug'

const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const EnBlogRoute = EnBlogRouteImport.update({
  id: '/en/blog',
  path: '/en/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const EnBlogIndexRoute = EnBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnBlogRoute,
} as any)
const EnBlogSlugRoute = EnBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/blog': typeof EnBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/en/blog': typeof EnBlogRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/blog/$slug'
    | '/en/blog'
    | '/blog/'
    | '/en/blog/$slug'
    | '/en/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/$slug' | '/blog' | '/en/blog/$slug' | '/en/blog'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/blog/$slug'
    | '/en/blog'
    | '/blog/'
    | '/en/blog/$slug'
    | '/en/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  EnBlogRoute: typeof EnBlogRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/en/blog': {
      id: '/en/blog'
      path: '/en/blog'
      fullPath: '/en/blog'
      preLoaderRoute: typeof EnBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/en/blog/': {
      id: '/en/blog/'
      path: '/'
      fullPath: '/en/blog/'
      preLoaderRoute: typeof EnBlogIndexRouteImport
      parentRoute: typeof EnBlogRoute
    }
    '/en/blog/$slug': {
      id: '/en/blog/$slug'
      path: '/$slug'
      fullPath: '/en/blog/$slug'
      preLoaderRoute: typeof EnBlogSlugRouteImport
      parentRoute: typeof EnBlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EnBlogRouteChildren {
  EnBlogSlugRoute: typeof EnBlogSlugRoute
  EnBlogIndexRoute: typeof EnBlogIndexRoute
}

const EnBlogRouteChildren: EnBlogRouteChildren = {
  EnBlogSlugRoute: EnBlogSlugRoute,
  EnBlogIndexRoute: EnBlogIndexRoute,
}

const EnBlogRouteWithChildren =
  EnBlogRoute._addFileChildren(EnBlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  EnBlogRoute: EnBlogRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
